class VMwarevCenterResourceModel(object):
    def __init__(self):
        self.user = ''
        self.password = ''
        self.default_dvswitch = ''
        self.holding_network = ''
        self.vm_cluster = ''
        self.vm_resource_pool = ''
        self.vm_storage = ''
        self.vm_location = ''
        self.shutdown_method = ''
        self.ovf_tool_path = ''
        self.execution_server_selector = '' 
        self.reserved_networks = ''
        self.default_datacenter = ''
