python driver_packager.py packeger_configs\\packeger_config_orchestrationDriver.txt orchestrationDriver
python driver_packager.py packeger_configs\\packager_config_deploymentServiceDriver.txt deploymentServiceDriver
python driver_packager.py packeger_configs\\packager_config_vCenterShell.txt vCenterShell