python driver_packager.py packeger_configs\\packeger_config_orchestration_service.txt orchestrationDriver
python driver_packager.py packeger_configs\\packager_config_deployment_service_driver.txt deploymentDriver
python driver_packager.py packeger_configs\\packager_config_vCenterShell.txt vCenterShellDriver